<a href="https://colab.research.google.com/github/pidugusureshbabu/psb/blob/master/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a=np.arange(1,5,1)

In [0]:
a

array([1, 2, 3, 4])

In [0]:
a=np.arange(1,5,11)
a

array([1])

In [0]:
a=np.arange(1,5,-1)
a

array([], dtype=int64)

In [0]:
a=np.arange(1,5,2)
a

array([1, 3])